# .github/workflows/publish.yml
name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.5.1
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Run tests
      run: |
        chmod +x scripts/test-distribution.bash
        ./scripts/test-distribution.bash --full

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/p/gracenote2epg
    permissions:
      id-token: write  # REQUIRED: needed for trusted publishing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
